### PR TITLE
test: Benchmark suite for multi-level partitioned tables with DuckDB metadata cache options

### LINKED ISSUE #57: Cache Parquet metadata in `pg_analytics`
### What feature are you requesting?

DuckDB has a feature, `enable_object_cache`, which can cache Parquet metadata in-memory. This is known to improve query performance. We would like to cache this on-disk, so that it can persist across queries.

### Why are you requesting this feature?

See above ^

### What is your proposed implementation for this feature?

I'm not sure, see https://github.com/paradedb/pg_analytics/pull/30 for reference

### Full Name:

Philippe Noël

### Affiliation:

ParadeDB

### PR DESCRIPTION
**Pull request by shamb0**
# Ticket(s) Closed
- Closes #57

## Why
- To provide a comprehensive analysis of query performance under different caching conditions for various sources supported by `pg_analytics`.

## How

The test function follows these steps:

1. **Parquet File Check**: Verifies if a Parquet file exists at a specified path. If not, generates the file.
2. **Data Loading**: Creates a DataFusion session context and loads the Parquet data into a DataFrame.
3. **S3 Setup**: Configures an S3 bucket to store partitioned data.
4. **Data Partitioning**: Partitions the data and uploads it to the S3 bucket.
5. **Database Setup**: Configures the necessary tables in a PostgreSQL database using the data stored in S3.
6. **Cache Configuration**: Sets up the required cache configuration, such as disk cache or memory cache.
7. **Benchmark Execution**: Runs target benchmark iterations using the `criterion` framework with different cache configurations.
8. **Benchmark Analysis**: Reports and analyzes the benchmark results using default metrics provided by `criterion`.

The following SQL statement is used to enable or disable the Parquet metadata (In-memory) cache:

```sql
SELECT duckdb_execute($$SET enable_object_cache={cache_setting}$$)
```

Where `cache_setting` is either "true" or "false" based on the test scenario.

## Benchmarking

To run the benchmarking, use the command:

```bash
cd ./pg_analytics_benches
RUST_LOG=info cargo bench -- --nocapture
```

### CODE REVIEW

**Comment by shamb0** [comment]
Hi @rebasedming,

I have kept the current PR in draft mode for now. We will consider it for review after we have merged [PR #115](https://github.com/paradedb/pg_analytics/pull/115).

**Review by philippemnoel — COMMENTED** [review]
Hey @shamb0! This is a good start, but I don't think it's quite what we had in mind.

DuckDB has some configuration settings here: https://duckdb.org/docs/configuration/overview#global-configuration-options

The user who requested this feature requested the ability to set the following option:

Capture d’écran, le 2024-09-03 à 06 47 15

In a permanent way. Currently, this option likely works but is not tested. It also only caches in memory. Implementing this feature would require:

- Confirming that we can currently set this option via our docs here: https://docs.paradedb.com/ingest/configuration/settings
- Test that the performance benefit is good
- Add code to cache the parquet metadata on-disk. There will be a few considerations for this like ensuring that the data can be cached successfully in various contexts (i.e. multiple databases, tablespaces, etc.) and that it gets deleted successfully if the user wants it to, for example if the user deletes the foreign table associated with the metadata.

You can inspire yourself from #30, which is a work-in-progress that caches the entire Parquet data over to disk.

**Comment by shamb0** [comment]
Hi @philippemnoel,

Thank you for your detailed feedback. I appreciate the guidance and would like to address the points you've raised. I've structured my response to align with your requirements:

1. DuckDB Global Configuration for In-memory Parquet Metadata Cache

I've made progress on the first two requirements you mentioned:

a) Confirming the option setting:
   I've implemented the `enable_object_cache` option in the test code as per https://docs.paradedb.com/ingest/configuration/settings. Here's a snippet:

   ```rust
   let cache_setting = if enable_cache { "true" } else { "false" };
   format!(
       "SELECT duckdb_execute($$SET enable_object_cache={}$$)",
       cache_setting
   )
   .execute(conn);
   ```

b) Performance testing:
   I've conducted benchmarking to verify the performance impact. Benchmarking shows a 48-50% performance improvement for the test query when enabling the in-memory cache for parquet metadata.

```
2024-09-03 21:18:43.404  INFO test_mlp_auto_sales::fixtures::tables::auto_sales: Completed data upload to S3
2024-09-03 21:18:43.404  INFO sqlx::postgres::notice: table "auto_sales" does not exist, skipping
2024-09-03 21:18:43.404  INFO sqlx::postgres::notice: server "auto_sales_server" does not exist, skipping
2024-09-03 21:18:43.404  INFO sqlx::postgres::notice: foreign-data wrapper "parquet_wrapper" does not exist, skipping
2024-09-03 21:18:43.404  INFO sqlx::postgres::notice: server "auto_sales_server" does not exist, skipping
2024-09-03 21:19:02.568  INFO test_mlp_auto_sales::fixtures::tables::auto_sales: Benchmark Results:
2024-09-03 21:19:02.568  INFO test_mlp_auto_sales::fixtures::tables::auto_sales: Cache Disabled:
2024-09-03 21:19:02.568  INFO test_mlp_auto_sales::fixtures::tables::auto_sales:   Average: 471.157795ms
2024-09-03 21:19:02.568  INFO test_mlp_auto_sales::fixtures::tables::auto_sales:   Minimum: 450.643718ms
2024-09-03 21:19:02.568  INFO test_mlp_auto_sales::fixtures::tables::auto_sales:   Maximum: 492.416808ms
2024-09-03 21:19:02.568  INFO test_mlp_auto_sales::fixtures::tables::auto_sales:   95th Percentile: 492.416808ms
2024-09-03 21:19:02.568  INFO test_mlp_auto_sales::fixtures::tables::auto_sales:   Standard Deviation: 12.599867ms (0.012600 seconds)
2024-09-03 21:19:02.568  INFO test_mlp_auto_sales::fixtures::tables::auto_sales: Cache Enabled:
2024-09-03 21:19:02.568  INFO test_mlp_auto_sales::fixtures::tables::auto_sales:   Average: 238.770521ms
2024-09-03 21:19:02.568  INFO test_mlp_auto_sales::fixtures::tables::auto_sales:   Minimum: 225.563416ms
2024-09-03 21:19:02.568  INFO test_mlp_auto_sales::fixtures::tables::auto_sales:   Maximum: 253.521833ms
2024-09-03 21:19:02.568  INFO test_mlp_auto_sales::fixtures::tables::auto_sales:   95th Percentile: 253.521833ms
2024-09-03 21:19:02.568  INFO test_mlp_auto_sales::fixtures::tables::auto_sales:   Standard Deviation: 8.684138ms (0.008684 seconds)
2024-09-03 21:19:02.568  INFO test_mlp_auto_sales::fixtures::tables::auto_sales: Final Cache Disabled:
2024-09-03 21:19:02.568  INFO test_mlp_auto_sales::fixtures::tables::auto_sales:   Average: 479.025158ms
2024-09-03 21:19:02.568  INFO test_mlp_auto_sales::fixtures::tables::auto_sales:   Minimum: 456.032762ms
2024-09-03 21:19:02.568  INFO test_mlp_auto_sales::fixtures::tables::auto_sales:   Maximum: 529.925317ms
2024-09-03 21:19:02.568  INFO test_mlp_auto_sales::fixtures::tables::auto_sales:   95th Percentile: 529.925317ms
2024-09-03 21:19:02.568  INFO test_mlp_auto_sales::fixtures::tables::auto_sales:   Standard Deviation: 20.999451ms (0.020999 seconds)
2024-09-03 21:19:02.568  INFO test_mlp_auto_sales::fixtures::tables::auto_sales: Performance improvement with cache: 50.15%
test test_duckdb_object_cache_performance ... ok
```
 
2. On-disk Cache for Parquet Metadata

I understand this is a crucial part of the feature request. From studying PR#30, I've learned about caching entire Parquet data to disk:

```rust
let relation = if cache { "TABLE" } else { "VIEW" };
Ok(format!("CREATE {relation} IF NOT EXISTS {schema_name}.{table_name} AS SELECT * FROM read_parquet({create_parquet_str})"))
```

This approach uses `CREATE TABLE` to mirror Parquet files from S3 to local disk when caching is enabled, managed by DuckDB through the Rust binder.

3. Parquet Metadata Local On-disk Cache

Regarding caching parquet metadata locally on-disk, I've found that DuckDB doesn't offer out-of-the-box support for this feature. However, there's an interesting possibility of using Apache Iceberg, as suggested in this discussion: https://github.com/duckdb/duckdb/issues/1622

image

Given that we've already integrated support for the DuckDB Iceberg extension in `pg_analytics`, I'd like to propose exploring the feasibility of:

a) Transforming Parquet files from S3 to Iceberg table format for local storage
b) Benchmarking the local cache performance with this approach

I understand the complexity involved in this transformation, but it seems promising based on the discussion thread. While @rebasedming is working on PR#30 for on-disk local cache for Parquet files, I could explore using Apache Iceberg as an alternative option for local disk caching in parallel.

I'd appreciate your thoughts on this approach. Should I proceed with exploring the Apache Iceberg option, or would you prefer I focus on a different aspect of the feature implementation?

Looking forward to your guidance on the next steps.

**Comment by philippemnoel** [comment]
> Hi @philippemnoel,
> 
> Thank you for your detailed feedback. I appreciate the guidance and would like to address the points you've raised. I've structured my response to align with your requirements:
> 
> ### 1. DuckDB Global Configuration for In-memory Parquet Metadata Cache
> I've made progress on the first two requirements you mentioned:
> 
> a) Confirming the option setting: I've implemented the `enable_object_cache` option in the test code as per https://docs.paradedb.com/ingest/configuration/settings. Here's a snippet:
> 
> ```rust
> let cache_setting = if enable_cache { "true" } else { "false" };
> format!(
>     "SELECT duckdb_execute($$SET enable_object_cache={}$$)",
>     cache_setting
> )
> .execute(conn);
> ```
> 
> b) Performance testing: I've conducted benchmarking to verify the performance impact. Benchmarking shows a 48-50% performance improvement for the test query when enabling the in-memory cache for parquet metadata.
> 
> ```
> 2024-09-03 21:18:43.404  INFO test_mlp_auto_sales::fixtures::tables::auto_sales: Completed data upload to S3
> 2024-09-03 21:18:43.404  INFO sqlx::postgres::notice: table "auto_sales" does not exist, skipping
> 2024-09-03 21:18:43.404  INFO sqlx::postgres::notice: server "auto_sales_server" does not exist, skipping
> 2024-09-03 21:18:43.404  INFO sqlx::postgres::notice: foreign-data wrapper "parquet_wrapper" does not exist, skipping
> 2024-09-03 21:18:43.404  INFO sqlx::postgres::notice: server "auto_sales_server" does not exist, skipping
> 2024-09-03 21:19:02.568  INFO test_mlp_auto_sales::fixtures::tables::auto_sales: Benchmark Results:
> 2024-09-03 21:19:02.568  INFO test_mlp_auto_sales::fixtures::tables::auto_sales: Cache Disabled:
> 2024-09-03 21:19:02.568  INFO test_mlp_auto_sales::fixtures::tables::auto_sales:   Average: 471.157795ms
> 2024-09-03 21:19:02.568  INFO test_mlp_auto_sales::fixtures::tables::auto_sales:   Minimum: 450.643718ms
> 2024-09-03 21:19:02.568  INFO test_mlp_auto_sales::fixtures::tables::auto_sales:   Maximum: 492.416808ms
> 2024-09-03 21:19:02.568  INFO test_mlp_auto_sales::fixtures::tables::auto_sales:   95th Percentile: 492.416808ms
> 2024-09-03 21:19:02.568  INFO test_mlp_auto_sales::fixtures::tables::auto_sales:   Standard Deviation: 12.599867ms (0.012600 seconds)
> 2024-09-03 21:19:02.568  INFO test_mlp_auto_sales::fixtures::tables::auto_sales: Cache Enabled:
> 2024-09-03 21:19:02.568  INFO test_mlp_auto_sales::fixtures::tables::auto_sales:   Average: 238.770521ms
> 2024-09-03 21:19:02.568  INFO test_mlp_auto_sales::fixtures::tables::auto_sales:   Minimum: 225.563416ms
> 2024-09-03 21:19:02.568  INFO test_mlp_auto_sales::fixtures::tables::auto_sales:   Maximum: 253.521833ms
> 2024-09-03 21:19:02.568  INFO test_mlp_auto_sales::fixtures::tables::auto_sales:   95th Percentile: 253.521833ms
> 2024-09-03 21:19:02.568  INFO test_mlp_auto_sales::fixtures::tables::auto_sales:   Standard Deviation: 8.684138ms (0.008684 seconds)
> 2024-09-03 21:19:02.568  INFO test_mlp_auto_sales::fixtures::tables::auto_sales: Final Cache Disabled:
> 2024-09-03 21:19:02.568  INFO test_mlp_auto_sales::fixtures::tables::auto_sales:   Average: 479.025158ms
> 2024-09-03 21:19:02.568  INFO test_mlp_auto_sales::fixtures::tables::auto_sales:   Minimum: 456.032762ms
> 2024-09-03 21:19:02.568  INFO test_mlp_auto_sales::fixtures::tables::auto_sales:   Maximum: 529.925317ms
> 2024-09-03 21:19:02.568  INFO test_mlp_auto_sales::fixtures::tables::auto_sales:   95th Percentile: 529.925317ms
> 2024-09-03 21:19:02.568  INFO test_mlp_auto_sales::fixtures::tables::auto_sales:   Standard Deviation: 20.999451ms (0.020999 seconds)
> 2024-09-03 21:19:02.568  INFO test_mlp_auto_sales::fixtures::tables::auto_sales: Performance improvement with cache: 50.15%
> test test_duckdb_object_cache_performance ... ok
> ```
> 
> ### 2. On-disk Cache for Parquet Metadata
> I understand this is a crucial part of the feature request. From studying PR#30, I've learned about caching entire Parquet data to disk:
> 
> ```rust
> let relation = if cache { "TABLE" } else { "VIEW" };
> Ok(format!("CREATE {relation} IF NOT EXISTS {schema_name}.{table_name} AS SELECT * FROM read_parquet({create_parquet_str})"))
> ```
> 
> This approach uses `CREATE TABLE` to mirror Parquet files from S3 to local disk when caching is enabled, managed by DuckDB through the Rust binder.
> 
> ### 3. Parquet Metadata Local On-disk Cache
> Regarding caching parquet metadata locally on-disk, I've found that DuckDB doesn't offer out-of-the-box support for this feature. However, there's an interesting possibility of using Apache Iceberg, as suggested in this discussion: [duckdb/duckdb#1622](https://github.com/duckdb/duckdb/issues/1622)
> 
> image
> 
> Given that we've already integrated support for the DuckDB Iceberg extension in `pg_analytics`, I'd like to propose exploring the feasibility of:
> 
> a) Transforming Parquet files from S3 to Iceberg table format for local storage b) Benchmarking the local cache performance with this approach
> 
> I understand the complexity involved in this transformation, but it seems promising based on the discussion thread. While @rebasedming is working on PR#30 for on-disk local cache for Parquet files, I could explore using Apache Iceberg as an alternative option for local disk caching in parallel.
> 
> I'd appreciate your thoughts on this approach. Should I proceed with exploring the Apache Iceberg option, or would you prefer I focus on a different aspect of the feature implementation?
> 
> Looking forward to your guidance on the next steps.

I'm very curious how the Iceberg approach approach would work! I wonder if it might be a viable alternative to the approach in #30. It would be helpful to have some benchmarks on this approach. It might even be preferrable to the DuckDB table approach, who knows.

**Comment by shamb0** [comment]
Hi @philippemnoel,

Apologies for the delay!

- I've merged the changes from [PR#30](https://github.com/paradedb/pg_analytics/pull/30).

- Additionally, I've integrated `criterion` benchmarking. You can find the benchmarking results for the Hive-style partitioned Parquet file source included.

## Data Source
- Hive-styled partitioned table
- Parquet format
- Stored in LocalStack S3 object store

## Benchmark Configuration
- Total Records: 10,000
- Batch Size: 512
- Sample Size: 10
- Measurement Time: 30 seconds
- Warm-up Time: 2 seconds

## Performance Results

| Scenario    | Configuration                                    | Median Time (ms) | Median Throughput (elem/s) |
|-------------|--------------------------------------------------|------------------|-----------------------------|
| Disk Cache  | with_disk_cache = true, with_mem_cache = false   | 2.8762           | 3.4769 M                    |
| Mem Cache   | with_disk_cache = false, with_mem_cache = true   | 246.21           | 40.616 K                    |
| Full Cache  | with_disk_cache = true, with_mem_cache = true    | 3.0520           | 3.2765 M                    |
| No Cache    | with_disk_cache = false, with_mem_cache = false  | 477.30           | 20.951 K                    |

## Key Observations
1. Disk Cache provides the best performance, with the highest throughput and lowest latency.
2. Full Cache (both disk and memory) performs slightly worse than Disk Cache alone.
3. Memory Cache alone is significantly slower than Disk Cache but faster than No Cache.
4. No Cache scenario has the poorest performance across all metrics.


- For `testcontainers`, I’m currently using a patched version to resolve an issue with async container cleanup. You can check out the callback trace [here](https://gist.githubusercontent.com/shamb0/7af01e4cc5c35a2389eccd124a6794c9/raw/d31dac4585597ca9482c3c3aa7b2bbacbfcafe7c/wk2437-testcontainers-backtrace.md). I'm planning to submit a PR to the `testcontainers` repo, and I’ll remove the patched version once the PR is merged.

- Lastly, I’m working on the `criterion` benchmarking results for the Iceberg table and will update you on that soon.

Thanks for your patience!

**Review by philippemnoel — COMMENTED** [review]
Hi @shamb0. This looks great! I'm really impressed by the caliber of work and the attention to details. Thank you for writing this.

We have a workspace called `cargo-paradedb` in the https://github.com/paradedb/paradedb repository, where we do benchmarking. We import this workspace here as part of our CI. The line isn't drawn perfectly well, but I would prefer is we kept to that workspace.

Would it be possible for you to investigate how to combine the two? Either commit this code to `paradedb/paradedb` and import it here, or maybe we should fully copy the code that's relevant from `cargo-paradedb` over to here?

**Comment by shamb0** [comment]
Hi @philippemnoel,

I've completed my investigation, and the prototype implementations are included in the following two Pair PRs.

https://github.com/paradedb/paradedb/pull/1703
https://github.com/paradedb/pg_analytics/pull/131

I agree with your suggestion on consolidating all benchmarking code under a single folder for easier maintenance and CI/CD testing. I've moved the benchmarking logic to the `cargo-paradedb` workspace as you recommended. Once the prototype implementation is reviewed and accepted, I will close the current PR.

Please let me know if you have any further thoughts or if there's anything else you'd like me to adjust!

**Comment by philippemnoel** [comment]
> Hi @philippemnoel,
> 
> I've completed my investigation, and the prototype implementations are included in the following two Pair PRs.
> 
> [paradedb/paradedb#1703](https://github.com/paradedb/paradedb/pull/1703) #131
> 
> I agree with your suggestion on consolidating all benchmarking code under a single folder for easier maintenance and CI/CD testing. I've moved the benchmarking logic to the `cargo-paradedb` workspace as you recommended. Once the prototype implementation is reviewed and accepted, I will close the current PR.
> 
> Please let me know if you have any further thoughts or if there's anything else you'd like me to adjust!

This is wonderful. Thank you @shamb0! @rebasedming is still swamped with some customer requests, but I'll make sure he finds some time to review this PR

**Comment by shamb0** [comment]
> > Hi @philippemnoel,
> > I've completed my investigation, and the prototype implementations are included in the following two Pair PRs.
> > [paradedb/paradedb#1703](https://github.com/paradedb/paradedb/pull/1703) #131
> > I agree with your suggestion on consolidating all benchmarking code under a single folder for easier maintenance and CI/CD testing. I've moved the benchmarking logic to the `cargo-paradedb` workspace as you recommended. Once the prototype implementation is reviewed and accepted, I will close the current PR.
> > Please let me know if you have any further thoughts or if there's anything else you'd like me to adjust!
> 
> This is wonderful. Thank you @shamb0! @rebasedming is still swamped with some customer requests, but I'll make sure he finds some time to review this PR

Sure, Thanks @philippemnoel

**Comment by philippemnoel** [comment]
Going to close this until a more scoped PR is raised.

**Pull request closed without merging**
