### PR TITLE
chore: Automatic UserMappingOptions methods implementation

### LINKED ISSUE #80: Automatically provide as_ref & iter methods to enums by using strum crate
### What feature are you requesting?

Automatically provide as_ref & iter methods to enums by using [strum](https://docs.rs/strum/latest/strum)
- [ ] CSVOption #81
- [ ] DeltaOption #82
- [ ] IcebergOption #83
- [ ] ParquetOption #84
- [ ] UserMappingOption #41

### Why are you requesting this feature?

Refactor and simplify the code 

### What is your proposed implementation for this feature?

Follow @evanxg852000's implementation in #41

### Full Name:

Weijun Huang

### Affiliation:

None

### LINKED ISSUE #82: Automatically provide as_ref & iter methods to enums on `DeltaOption` by using strum
### What feature are you requesting?

Automatically provide as_ref & iter methods to enums on `DeltaOption` by using [strum](https://docs.rs/strum/latest/strum)

### Why are you requesting this feature?

Refactor and simplify the code 

### What is your proposed implementation for this feature?

Follow @evanxg852000's implementation in #41

### Full Name:

Weijun Huang

### Affiliation:

None

### LINKED ISSUE #83: Automatically provide as_ref & iter methods to enums on `IcebergOption` by using strum
### What feature are you requesting?

Automatically provide as_ref & iter methods to enums on `IcebergOption` by using strum

### Why are you requesting this feature?

Refactor and simplify the code 

### What is your proposed implementation for this feature?

Follow @evanxg852000's implementation in #41

### Full Name:

Weijun Huang

### Affiliation:

None

### LINKED ISSUE #84: Automatically provide as_ref & iter methods to enums on `ParquetOption` by using strum
### What feature are you requesting?

Automatically provide as_ref & iter methods to enums on `ParquetOption` by using strum

### Why are you requesting this feature?

Refactor and simplify the code 

### What is your proposed implementation for this feature?

Follow @evanxg852000's implementation in #41

### Full Name:

Weijun Huang

### Affiliation:

None

### PR DESCRIPTION
**Pull request by evanxg852000**
# Ticket(s) Closed

- Closes #82 
- Closes #83 
- Closes #84 
- Closes #80 

## What
Added a dependency on [strum](https://docs.rs/strum/latest/strum) create to automatically provide `as_ref` & `iter` methods to enums. More can be added if needed.
## Why
The strum can be used to remove useful manual implementations
## Tests
Made sure the `as_ref` & `iter` methods provide the expected output.

### CODE REVIEW

**Comment by Weijun-H** [comment]
I’m uncertain if adding new dependencies just to time this refactoring is justified.

**Comment by evanxg852000** [comment]
@Weijun-H 👍🏾 Indeed this was also my concern given it's currently used in one place. However, I discussed this with a team member. It was deemed ok since it's lightweight. It would be perfectly valid if the consensus is to put this aside for now to avoid further dependencies. It's not a critical change anyway.

**Review by rebasedming — COMMENTED** [review]
Nice! If we're going to refactor, let's apply this change everywhere.

**Comment by Weijun-H** [comment]
> Nice! If we're going to refactor, let's apply this change everywhere.

How about merging this PR first and then splitting the refactoring task into multiple "good first issue" tasks?

**Comment by philippemnoel** [comment]
> > Nice! If we're going to refactor, let's apply this change everywhere.
> 
> How about merging this PR first and then splitting the refactoring task into multiple "good first issue" tasks?

That sounds great. Could you please help open up the issues and link them in the PR here? Then we can merge the PR

**Comment by Weijun-H** [comment]
> > > Nice! If we're going to refactor, let's apply this change everywhere.
> > 
> > 
> > How about merging this PR first and then splitting the refactoring task into multiple "good first issue" tasks?
> 
> That sounds great. Could you please help open up the issues and link them in the PR here? Then we can merge the PR

file a ticket #80 to track

**Review by rebasedming — APPROVED** [review]

**Pull request merged**
